apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java
  labels:
    app: java
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: demo-java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: demo-java
          image: gcr.io/k8s-cluster-295906/demo-java:latest
          ports:
            - containerPort: 8080
