apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  selector:
    deployment: demo-java
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP