apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: demo-nodejs
          image: gcr.io/k8s-cluster-295906/demo-nodejs:latest
          ports:
            - containerPort: 8080