apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    deployment: demo-nodejs
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP