apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    deployment: demo-nodejs
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP